import { createElement } from "react";
import {
  SiProxmox,
  SiVmware,
  SiDocker,
  SiKubernetes,
  SiPodman,
  SiVirtualbox,
  SiKalilinux,
  SiUbuntu,
  SiDebian,
  SiAlpinelinux,
  SiFedora,
  SiArchlinux,
  SiFreebsd,
  SiRaspberrypi,
  SiLinux,
  SiCentos,
  SiOpensuse,
  SiRockylinux,
  SiAlmalinux,
  SiAmazonwebservices,
  SiGooglecloud,
  SiCloudflare,
  SiDigitalocean,
  SiOracle,
  SiHetzner,
  SiNginx,
  SiTraefikproxy,
  SiOpenvpn,
  SiWireshark,
  SiPfsense,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiRedis,
  SiMariadb,
  SiInfluxdb,
  SiSqlite,
  SiGrafana,
  SiPrometheus,
  SiElasticsearch,
  SiKibana,
  SiDatadog,
  SiAnsible,
  SiTerraform,
  SiGit,
  SiGithub,
  SiGitlab,
  SiJenkins,
  SiNextcloud,
  SiGitea,
  SiJellyfin,
  SiPlex,
  SiHomeassistant,
  SiN8N,
  SiVault,
  SiOpenssl,
} from "react-icons/si";
import type { ComponentType } from "react";

export type IconRegistryEntry = {
  key: string;
  label: string;
  brandColor: string;
  category: string;
};

export const ICON_REGISTRY: IconRegistryEntry[] = [
  // Virtualization
  { key: "SiProxmox", label: "Proxmox", brandColor: "#E57000", category: "Virtualization" },
  { key: "SiVmware", label: "VMware", brandColor: "#607078", category: "Virtualization" },
  { key: "SiDocker", label: "Docker", brandColor: "#2496ED", category: "Virtualization" },
  { key: "SiKubernetes", label: "Kubernetes", brandColor: "#326CE5", category: "Virtualization" },
  { key: "SiPodman", label: "Podman", brandColor: "#892CA0", category: "Virtualization" },
  { key: "SiVirtualbox", label: "VirtualBox", brandColor: "#183A61", category: "Virtualization" },

  // Operating Systems
  { key: "SiLinux", label: "Linux", brandColor: "#FCC624", category: "Operating Systems" },
  { key: "SiUbuntu", label: "Ubuntu", brandColor: "#E95420", category: "Operating Systems" },
  { key: "SiDebian", label: "Debian", brandColor: "#A81D33", category: "Operating Systems" },
  { key: "SiKalilinux", label: "Kali Linux", brandColor: "#557C94", category: "Operating Systems" },
  { key: "SiAlpinelinux", label: "Alpine", brandColor: "#0D597F", category: "Operating Systems" },
  { key: "SiFedora", label: "Fedora", brandColor: "#51A2DA", category: "Operating Systems" },
  { key: "SiArchlinux", label: "Arch Linux", brandColor: "#1793D1", category: "Operating Systems" },
  { key: "SiCentos", label: "CentOS", brandColor: "#932279", category: "Operating Systems" },
  { key: "SiRockylinux", label: "Rocky Linux", brandColor: "#10B981", category: "Operating Systems" },
  { key: "SiAlmalinux", label: "AlmaLinux", brandColor: "#FF4B4B", category: "Operating Systems" },
  { key: "SiOpensuse", label: "openSUSE", brandColor: "#73BA25", category: "Operating Systems" },
  { key: "SiFreebsd", label: "FreeBSD", brandColor: "#AB2B28", category: "Operating Systems" },
  { key: "SiRaspberrypi", label: "Raspberry Pi", brandColor: "#A22846", category: "Operating Systems" },

  // Cloud
  { key: "SiAmazonwebservices", label: "AWS", brandColor: "#FF9900", category: "Cloud" },
  { key: "SiGooglecloud", label: "Google Cloud", brandColor: "#4285F4", category: "Cloud" },
  { key: "SiCloudflare", label: "Cloudflare", brandColor: "#F38020", category: "Cloud" },
  { key: "SiDigitalocean", label: "DigitalOcean", brandColor: "#0080FF", category: "Cloud" },
  { key: "SiOracle", label: "Oracle Cloud", brandColor: "#F80000", category: "Cloud" },
  { key: "SiHetzner", label: "Hetzner", brandColor: "#D50C2D", category: "Cloud" },

  // Networking
  { key: "SiNginx", label: "Nginx", brandColor: "#009639", category: "Networking" },
  { key: "SiTraefikproxy", label: "Traefik", brandColor: "#24A1C1", category: "Networking" },
  { key: "SiOpenvpn", label: "OpenVPN", brandColor: "#EA7E20", category: "Networking" },
  { key: "SiWireshark", label: "Wireshark", brandColor: "#1679A7", category: "Networking" },
  { key: "SiPfsense", label: "pfSense", brandColor: "#212121", category: "Networking" },

  // Databases
  { key: "SiPostgresql", label: "PostgreSQL", brandColor: "#4169E1", category: "Databases" },
  { key: "SiMysql", label: "MySQL", brandColor: "#4479A1", category: "Databases" },
  { key: "SiMongodb", label: "MongoDB", brandColor: "#47A248", category: "Databases" },
  { key: "SiRedis", label: "Redis", brandColor: "#FF4438", category: "Databases" },
  { key: "SiMariadb", label: "MariaDB", brandColor: "#003545", category: "Databases" },
  { key: "SiInfluxdb", label: "InfluxDB", brandColor: "#22ADF6", category: "Databases" },
  { key: "SiSqlite", label: "SQLite", brandColor: "#003B57", category: "Databases" },

  // Monitoring
  { key: "SiGrafana", label: "Grafana", brandColor: "#F46800", category: "Monitoring" },
  { key: "SiPrometheus", label: "Prometheus", brandColor: "#E6522C", category: "Monitoring" },
  { key: "SiElasticsearch", label: "Elasticsearch", brandColor: "#005571", category: "Monitoring" },
  { key: "SiKibana", label: "Kibana", brandColor: "#005571", category: "Monitoring" },
  { key: "SiDatadog", label: "Datadog", brandColor: "#632CA6", category: "Monitoring" },

  // DevOps
  { key: "SiAnsible", label: "Ansible", brandColor: "#EE0000", category: "DevOps" },
  { key: "SiTerraform", label: "Terraform", brandColor: "#7B42BC", category: "DevOps" },
  { key: "SiGit", label: "Git", brandColor: "#F05032", category: "DevOps" },
  { key: "SiGithub", label: "GitHub", brandColor: "#181717", category: "DevOps" },
  { key: "SiGitlab", label: "GitLab", brandColor: "#FC6D26", category: "DevOps" },
  { key: "SiJenkins", label: "Jenkins", brandColor: "#D24939", category: "DevOps" },
  { key: "SiVault", label: "Vault", brandColor: "#FFEC6E", category: "DevOps" },
  { key: "SiOpenssl", label: "OpenSSL", brandColor: "#721412", category: "DevOps" },

  // Self-hosted
  { key: "SiNextcloud", label: "Nextcloud", brandColor: "#0082C9", category: "Self-hosted" },
  { key: "SiGitea", label: "Gitea", brandColor: "#609926", category: "Self-hosted" },
  { key: "SiJellyfin", label: "Jellyfin", brandColor: "#00A4DC", category: "Self-hosted" },
  { key: "SiPlex", label: "Plex", brandColor: "#E5A00D", category: "Self-hosted" },
  { key: "SiHomeassistant", label: "Home Assistant", brandColor: "#18BCF2", category: "Self-hosted" },
  { key: "SiN8N", label: "n8n", brandColor: "#EA4B71", category: "Self-hosted" },
];

// Map from key string to component — avoids dynamic imports at render time
const SI_MAP: Record<string, ComponentType<{ size?: number }>> = {
  SiProxmox,
  SiVmware,
  SiDocker,
  SiKubernetes,
  SiPodman,
  SiVirtualbox,
  SiKalilinux,
  SiUbuntu,
  SiDebian,
  SiAlpinelinux,
  SiFedora,
  SiArchlinux,
  SiFreebsd,
  SiRaspberrypi,
  SiLinux,
  SiCentos,
  SiOpensuse,
  SiRockylinux,
  SiAlmalinux,
  SiAmazonwebservices,
  SiGooglecloud,
  SiCloudflare,
  SiDigitalocean,
  SiOracle,
  SiHetzner,
  SiNginx,
  SiTraefikproxy,
  SiOpenvpn,
  SiWireshark,
  SiPfsense,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiRedis,
  SiMariadb,
  SiInfluxdb,
  SiSqlite,
  SiGrafana,
  SiPrometheus,
  SiElasticsearch,
  SiKibana,
  SiDatadog,
  SiAnsible,
  SiTerraform,
  SiGit,
  SiGithub,
  SiGitlab,
  SiJenkins,
  SiNextcloud,
  SiGitea,
  SiJellyfin,
  SiPlex,
  SiHomeassistant,
  SiN8N,
  SiVault,
  SiOpenssl,
};

export function getRegistryIcon(key: string): React.ReactElement | null {
  const C = SI_MAP[key];
  if (!C) return null;
  return createElement(C, { size: 20 });
}
