import { ArrowLeft } from "lucide-react";
import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950">
      <div className="container mx-auto px-6 py-12 max-w-4xl">
        {/* Back Button */}
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-slate-400 hover:text-slate-200 transition-colors mb-8"
        >
          <ArrowLeft size={20} />
          <span>Back to Lab</span>
        </Link>

        {/* Content */}
        <div className="bg-slate-900/50 backdrop-blur-xl border border-slate-800/50 rounded-2xl p-8 md:p-12">
          <h1 className="text-4xl font-bold text-slate-100 mb-4">Terms of Service</h1>
          <p className="text-slate-400 mb-8">Last updated: February 15, 2026</p>

          <div className="prose prose-invert prose-slate max-w-none">
            {/* AI Chat Section */}
            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-slate-200 mb-4">🤖 AI-Powered Chat</h2>
              <p className="text-slate-300 mb-4">
                This site uses AI (Large Language Model) to answer questions about infrastructure topology.
              </p>
              <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-4 mb-4">
                <h3 className="text-lg font-semibold text-yellow-400 mb-2">⚠️ Important Disclaimer</h3>
                <ul className="text-slate-300 space-y-2 list-disc list-inside">
                  <li>Responses are generated by AI and may contain errors or inaccuracies</li>
                  <li>Not professional, technical, or expert advice</li>
                  <li>For demonstration and educational purposes only</li>
                  <li>Always verify critical information independently</li>
                  <li>No warranties or guarantees provided</li>
                </ul>
              </div>
            </section>

            {/* Rate Limiting */}
            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-slate-200 mb-4">⏱️ Rate Limiting</h2>
              <p className="text-slate-300 mb-4">
                To prevent abuse and ensure fair access, the following limits are enforced:
              </p>
              <ul className="text-slate-300 space-y-2 list-disc list-inside">
                <li><strong>10 requests per minute</strong> per IP address</li>
                <li><strong>2,000 characters maximum</strong> per message</li>
                <li><strong>20 messages maximum</strong> per conversation</li>
                <li><strong>30 seconds timeout</strong> per request</li>
              </ul>
              <p className="text-slate-400 text-sm mt-4">
                Exceeding these limits will result in temporary blocking (HTTP 429 error).
              </p>
            </section>

            {/* Data & Privacy */}
            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-slate-200 mb-4">🔒 Data & Privacy</h2>
              <div className="text-slate-300 space-y-3">
                <p><strong>What we collect:</strong></p>
                <ul className="list-disc list-inside space-y-1 ml-4">
                  <li>No personal information or account data</li>
                  <li>No tracking cookies</li>
                  <li>Temporary session data via localStorage (layout preferences, admin status)</li>
                  <li>IP addresses for rate limiting (not stored permanently)</li>
                </ul>

                <p className="mt-4"><strong>What we DON'T do:</strong></p>
                <ul className="list-disc list-inside space-y-1 ml-4">
                  <li>Chat conversations are NOT stored or logged</li>
                  <li>No analytics or tracking scripts</li>
                  <li>No data sold to third parties</li>
                  <li>No user profiles or databases</li>
                </ul>

                <p className="mt-4"><strong>Third-party services:</strong></p>
                <ul className="list-disc list-inside space-y-1 ml-4">
                  <li>LLM Provider: OpenRouter/OpenAI (chat responses only)</li>
                  <li>Hosting: Vercel (infrastructure)</li>
                </ul>
              </div>
            </section>

            {/* Cookies & localStorage */}
            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-slate-200 mb-4">🍪 Cookies & Local Storage</h2>
              <p className="text-slate-300 mb-4">
                This site uses <strong>localStorage</strong> (browser storage, not cookies) for:
              </p>
              <ul className="text-slate-300 space-y-2 list-disc list-inside">
                <li><strong>Layout preferences:</strong> Save your custom diagram layouts</li>
                <li><strong>Admin session:</strong> Remember admin status after authentication</li>
              </ul>
              <p className="text-slate-400 text-sm mt-4">
                This data stays in your browser and is never sent to our servers. You can clear it anytime via browser settings.
              </p>
            </section>

            {/* Acceptable Use */}
            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-slate-200 mb-4">✅ Acceptable Use</h2>
              <p className="text-slate-300 mb-3">You may NOT:</p>
              <ul className="text-slate-300 space-y-2 list-disc list-inside">
                <li>Bypass or abuse rate limits</li>
                <li>Attempt to jailbreak or manipulate the AI</li>
                <li>Automate requests or scrape data</li>
                <li>Use for illegal or malicious purposes</li>
                <li>Decompile, reverse engineer, or modify the code without permission</li>
                <li>Impersonate administrators or other users</li>
              </ul>
              <p className="text-slate-400 text-sm mt-4">
                Violations may result in immediate termination of access.
              </p>
            </section>

            {/* Liability */}
            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-slate-200 mb-4">⚖️ Limitation of Liability</h2>
              <p className="text-slate-300">
                This service is provided <strong>"AS IS"</strong> without warranties of any kind, express or implied.
                Use at your own risk. The creator is not liable for:
              </p>
              <ul className="text-slate-300 space-y-2 list-disc list-inside mt-3">
                <li>Inaccurate or incorrect AI responses</li>
                <li>Service downtime or interruptions</li>
                <li>Loss of data or settings</li>
                <li>Any damages arising from use of this service</li>
              </ul>
            </section>

            {/* Changes to Terms */}
            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-slate-200 mb-4">📝 Changes to Terms</h2>
              <p className="text-slate-300">
                These terms may be updated at any time. Changes take effect immediately upon posting.
                Continued use constitutes acceptance of updated terms.
              </p>
            </section>

            {/* Contact */}
            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-slate-200 mb-4">📧 Contact</h2>
              <p className="text-slate-300">
                Questions or concerns about these terms?{" "}
                <a 
                  href="https://www.villaarreola.com" 
                  className="text-blue-400 hover:text-blue-300 underline"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Contact me
                </a>
              </p>
            </section>

            {/* Footer */}
            <div className="border-t border-slate-700 pt-6 mt-12">
              <p className="text-slate-500 text-sm">
                By using this site, you acknowledge that you have read and agree to these Terms of Service.
              </p>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
